/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as BlogAndEventsRouteImport } from './routes/blog-and-events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BnIndexRouteImport } from './routes/bn/index'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as BnTermsAndConditionsRouteImport } from './routes/bn/terms-and-conditions'
import { Route as BnServicesRouteImport } from './routes/bn/services'
import { Route as BnPrivacyPolicyRouteImport } from './routes/bn/privacy-policy'
import { Route as BnContactRouteImport } from './routes/bn/contact'
import { Route as BnBookAppointmentRouteImport } from './routes/bn/book-appointment'
import { Route as BnBlogAndEventsRouteImport } from './routes/bn/blog-and-events'
import { Route as BnAboutRouteImport } from './routes/bn/about'
import { Route as BnServicesSlugRouteImport } from './routes/bn/services_.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicAppointmentRouteImport } from './routes/api/public/appointment'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAndEventsRoute = BlogAndEventsRouteImport.update({
  id: '/blog-and-events',
  path: '/blog-and-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BnIndexRoute = BnIndexRouteImport.update({
  id: '/bn/',
  path: '/bn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BnTermsAndConditionsRoute = BnTermsAndConditionsRouteImport.update({
  id: '/bn/terms-and-conditions',
  path: '/bn/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const BnServicesRoute = BnServicesRouteImport.update({
  id: '/bn/services',
  path: '/bn/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BnPrivacyPolicyRoute = BnPrivacyPolicyRouteImport.update({
  id: '/bn/privacy-policy',
  path: '/bn/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BnContactRoute = BnContactRouteImport.update({
  id: '/bn/contact',
  path: '/bn/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BnBookAppointmentRoute = BnBookAppointmentRouteImport.update({
  id: '/bn/book-appointment',
  path: '/bn/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const BnBlogAndEventsRoute = BnBlogAndEventsRouteImport.update({
  id: '/bn/blog-and-events',
  path: '/bn/blog-and-events',
  getParentRoute: () => rootRouteImport,
} as any)
const BnAboutRoute = BnAboutRouteImport.update({
  id: '/bn/about',
  path: '/bn/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BnServicesSlugRoute = BnServicesSlugRouteImport.update({
  id: '/bn/services_/$slug',
  path: '/bn/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppointmentRoute = ApiPublicAppointmentRouteImport.update({
  id: '/api/public/appointment',
  path: '/api/public/appointment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog-and-events': typeof BlogAndEventsRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/bn/about': typeof BnAboutRoute
  '/bn/blog-and-events': typeof BnBlogAndEventsRoute
  '/bn/book-appointment': typeof BnBookAppointmentRoute
  '/bn/contact': typeof BnContactRoute
  '/bn/privacy-policy': typeof BnPrivacyPolicyRoute
  '/bn/services': typeof BnServicesRoute
  '/bn/terms-and-conditions': typeof BnTermsAndConditionsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/bn/': typeof BnIndexRoute
  '/api/public/appointment': typeof ApiPublicAppointmentRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/bn/services/$slug': typeof BnServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog-and-events': typeof BlogAndEventsRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/bn/about': typeof BnAboutRoute
  '/bn/blog-and-events': typeof BnBlogAndEventsRoute
  '/bn/book-appointment': typeof BnBookAppointmentRoute
  '/bn/contact': typeof BnContactRoute
  '/bn/privacy-policy': typeof BnPrivacyPolicyRoute
  '/bn/services': typeof BnServicesRoute
  '/bn/terms-and-conditions': typeof BnTermsAndConditionsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/bn': typeof BnIndexRoute
  '/api/public/appointment': typeof ApiPublicAppointmentRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/bn/services/$slug': typeof BnServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog-and-events': typeof BlogAndEventsRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/bn/about': typeof BnAboutRoute
  '/bn/blog-and-events': typeof BnBlogAndEventsRoute
  '/bn/book-appointment': typeof BnBookAppointmentRoute
  '/bn/contact': typeof BnContactRoute
  '/bn/privacy-policy': typeof BnPrivacyPolicyRoute
  '/bn/services': typeof BnServicesRoute
  '/bn/terms-and-conditions': typeof BnTermsAndConditionsRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/bn/': typeof BnIndexRoute
  '/api/public/appointment': typeof ApiPublicAppointmentRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/bn/services_/$slug': typeof BnServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog-and-events'
    | '/book-appointment'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/bn/about'
    | '/bn/blog-and-events'
    | '/bn/book-appointment'
    | '/bn/contact'
    | '/bn/privacy-policy'
    | '/bn/services'
    | '/bn/terms-and-conditions'
    | '/services/$slug'
    | '/bn/'
    | '/api/public/appointment'
    | '/api/public/contact'
    | '/bn/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog-and-events'
    | '/book-appointment'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/bn/about'
    | '/bn/blog-and-events'
    | '/bn/book-appointment'
    | '/bn/contact'
    | '/bn/privacy-policy'
    | '/bn/services'
    | '/bn/terms-and-conditions'
    | '/services/$slug'
    | '/bn'
    | '/api/public/appointment'
    | '/api/public/contact'
    | '/bn/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog-and-events'
    | '/book-appointment'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/bn/about'
    | '/bn/blog-and-events'
    | '/bn/book-appointment'
    | '/bn/contact'
    | '/bn/privacy-policy'
    | '/bn/services'
    | '/bn/terms-and-conditions'
    | '/services_/$slug'
    | '/bn/'
    | '/api/public/appointment'
    | '/api/public/contact'
    | '/bn/services_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogAndEventsRoute: typeof BlogAndEventsRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BnAboutRoute: typeof BnAboutRoute
  BnBlogAndEventsRoute: typeof BnBlogAndEventsRoute
  BnBookAppointmentRoute: typeof BnBookAppointmentRoute
  BnContactRoute: typeof BnContactRoute
  BnPrivacyPolicyRoute: typeof BnPrivacyPolicyRoute
  BnServicesRoute: typeof BnServicesRoute
  BnTermsAndConditionsRoute: typeof BnTermsAndConditionsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BnIndexRoute: typeof BnIndexRoute
  ApiPublicAppointmentRoute: typeof ApiPublicAppointmentRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  BnServicesSlugRoute: typeof BnServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-and-events': {
      id: '/blog-and-events'
      path: '/blog-and-events'
      fullPath: '/blog-and-events'
      preLoaderRoute: typeof BlogAndEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/': {
      id: '/bn/'
      path: '/bn'
      fullPath: '/bn/'
      preLoaderRoute: typeof BnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/terms-and-conditions': {
      id: '/bn/terms-and-conditions'
      path: '/bn/terms-and-conditions'
      fullPath: '/bn/terms-and-conditions'
      preLoaderRoute: typeof BnTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/services': {
      id: '/bn/services'
      path: '/bn/services'
      fullPath: '/bn/services'
      preLoaderRoute: typeof BnServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/privacy-policy': {
      id: '/bn/privacy-policy'
      path: '/bn/privacy-policy'
      fullPath: '/bn/privacy-policy'
      preLoaderRoute: typeof BnPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/contact': {
      id: '/bn/contact'
      path: '/bn/contact'
      fullPath: '/bn/contact'
      preLoaderRoute: typeof BnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/book-appointment': {
      id: '/bn/book-appointment'
      path: '/bn/book-appointment'
      fullPath: '/bn/book-appointment'
      preLoaderRoute: typeof BnBookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/blog-and-events': {
      id: '/bn/blog-and-events'
      path: '/bn/blog-and-events'
      fullPath: '/bn/blog-and-events'
      preLoaderRoute: typeof BnBlogAndEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/about': {
      id: '/bn/about'
      path: '/bn/about'
      fullPath: '/bn/about'
      preLoaderRoute: typeof BnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/services_/$slug': {
      id: '/bn/services_/$slug'
      path: '/bn/services/$slug'
      fullPath: '/bn/services/$slug'
      preLoaderRoute: typeof BnServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointment': {
      id: '/api/public/appointment'
      path: '/api/public/appointment'
      fullPath: '/api/public/appointment'
      preLoaderRoute: typeof ApiPublicAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogAndEventsRoute: BlogAndEventsRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BnAboutRoute: BnAboutRoute,
  BnBlogAndEventsRoute: BnBlogAndEventsRoute,
  BnBookAppointmentRoute: BnBookAppointmentRoute,
  BnContactRoute: BnContactRoute,
  BnPrivacyPolicyRoute: BnPrivacyPolicyRoute,
  BnServicesRoute: BnServicesRoute,
  BnTermsAndConditionsRoute: BnTermsAndConditionsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BnIndexRoute: BnIndexRoute,
  ApiPublicAppointmentRoute: ApiPublicAppointmentRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  BnServicesSlugRoute: BnServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
